### ISSUE TITLE
Please add sample Schemas and Resolvers to handle Pagination requests.

### ISSUE THREAD

**Issue by dbx834** [apollographql/dev.apollodata.com#29]
Hi,

I was studying http://dev.apollodata.com/react/pagination.html#relay-cursors, and the client code is very clear. However, it's difficult to figure out a way to write schemas and resolvers for pagination.

Perhaps a section under http://dev.apollodata.com/tools/graphql-tools/generate-schema.html on responding to Pagniation requests would be nice?

Thanks!

**Comment by dbx834** [comment]
I found some hints here, [http://pcarion.com/2015/09/20/GraphQL-connections/](http://pcarion.com/2015/09/20/GraphQL-connections/) ("GraphQL relaty relation navigation")

**Comment by stubailo** [comment]
I think this would be best opened as an issue here: https://github.com/apollographql/tools-docs

I think a new page about pagination under the `graphql-tools` section could be neat!

I agree there aren't a lot of examples out there for how to write this stuff.
